[package]
name = "harpoxide"
version = "0.1.0"
authors = ["Brandon Pitman <brandon.pitman@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.13"
protobuf = "2"
rand = "0.7"
scrypt = { version = "0.5", default-features = false }
sodiumoxide = "0.2"
tempfile = "3"
walkdir = "2"

[dev-dependencies]
tempdir = "0.3"

[build-dependencies]
protoc-rust = "2"
